name: docker

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 03081983/buildtagpush
          tag_with_ref: true
          tag_with_sha: true
          cache_froms: 03081983/buildtagpush:latest
        env:
          DOCKER_BUILDKIT: 1
          
on:
  push:
    branches:
      - buildkit
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: buildkit
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 03081983/buildtagpush-buildkit
          tag_with_ref: true
          tag_with_sha: true
          cache_froms: 03081983/buildtagpush-buildkit:latest
        env:
          DOCKER_BUILDKIT: 1
